---
- name: Setup office_music
  hosts: office_music
  become: yes
  tasks:
  - name: Install software
    ansible.builtin.package:
      name:
        - mpv
        - chromium
        - shairport-sync
        - yt-dlp
        - uxplay
        - gstreamer1.0-plugins-base
        - gstreamer1.0-libav
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-gl
        - gstreamer1.0-tools
      state: latest
  - name: Copy shairport config file
    ansible.builtin.copy:
      src: shairport-sync.conf
      dest: /etc/shairport-sync.conf
  - name: Make mpv config file destination
    file:
      path: /home/phajas/.config/mpv
      state: directory
  - name: Copy mpv config file
    ansible.builtin.copy:
      src: mpv.conf
      dest: /home/phajas/.config/mpv/mpv.conf
  - name: Make uxplay config file destination
    file:
      path: /home/phajas/.config/uxplay
      state: directory
  - name: Copy uxplay config file
    ansible.builtin.copy:
      src: uxplayrc
      dest: /home/phajas/.config/uxplayrc
  - name: Ensure shairport is running
    ansible.builtin.service:
      name: shairport-sync
      state: started
    become: yes
  - name: Restart shairport
    ansible.builtin.service:
      name: shairport-sync
      state: restarted
  - name: Disable sleep
    ansible.builtin.systemd:
      name: sleep.target
      enabled: false
      masked: true
  - name: Disable suspend
    ansible.builtin.systemd:
      name: suspend.target
      enabled: false
      masked: true
  - name: Disable hibernate
    ansible.builtin.systemd:
      name: hibernate.target
      enabled: false
      masked: true
  - name: Disable hybrid-sleep
    ansible.builtin.systemd:
      name: hybrid-sleep.target
      enabled: false
      masked: true
