---
- name: setup steamdeck
  hosts: steamdeck
  become: yes
  tasks:
    - name: start ssh
      ansible.builtin.systemd:
        state: started
        name: sshd
    - name: install packages
      community.general.flatpak:
        name:
          - ca.parallel_launcher.ParallelLauncher
          - com.github.iwalton3.jellyfin-media-player
          - com.heroicgameslauncher.hgl
          - io.gitlab.librewolf-community
          - io.mpv.Mpv
    - name: grab emudeck installer
      ansible.builtin.get_url:
        url: https://www.emudeck.com/EmuDeck.desktop
        dest: /home/deck/Desktop/InstallEmuDeck.desktop
    - name: emudeck files
      become: false
      ansible.posix.synchronize:
        src: ~/Emulation
        dest: /run/media/mmcblk0p1/
        mode: push
