# window
autofit=400
geometry=-0-0
screen=0
on-all-workspaces=yes
ontop=yes
keepaspect=yes

# caching
cache=yes
cache-pause=yes
cache-pause-initial=yes
demuxer-max-bytes=150MiB
demuxer-max-back-bytes=50MiB

# video output
vo=gpu-next
hwdec=auto

# performance
profile=fast
video-sync=audio
hr-seek=no

# yt-dlp
ytdl-format="bestvideo[height<=1080]+bestaudio/best[height<=1080]"

# shader (no more for now)
# glsl-shader="~~/FSRCNNX_x2_8-0-4-1.glsl"
