require("phajas.set")
require("phajas.lazy")
require("phajas.remap")
require("phajas.globals")
require("phajas.nb")
require("phajas.wiki")

-- before LSP
require("phajas.plugins.mason")

require("phajas.plugins.blame_line")
require("phajas.plugins.catppuccin")
require("phajas.plugins.cmp")
require("phajas.plugins.commentary")
require("phajas.plugins.fugitive")
require("phajas.plugins.gitsigns")
require("phajas.plugins.harpoon")
require("phajas.plugins.lsp")
require("phajas.plugins.lualine")
require("phajas.plugins.nvim-colorizer")
require("phajas.plugins.oil")
require("phajas.plugins.table-mode")
require("phajas.plugins.telescope")
require("phajas.plugins.treesitter")
require("phajas.plugins.undotree")
require("phajas.plugins.zen-mode")

