vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gb", ":G blame --date=short<CR>")
vim.keymap.set("n", "<leader>ga", ":G add %<CR>")
vim.keymap.set("n", "<leader>gm", ":G commit<CR>")
vim.keymap.set("n", "<leader>gps", ":G push origin HEAD<CR>")
vim.keymap.set("n", "<leader>gpS", ":G push<CR>")
vim.keymap.set("n", "<leader>gpl", ":G pull<CR>")
vim.keymap.set("n", "<leader>gd", ":Gdiffsplit<CR>")
vim.keymap.set("n", "<leader>gl", ":G log<CR>")
