---
- name: Enable rsync daemon on torch
  hosts: torch
  become: true
  tasks:
    - name: Create rsyncd.conf
      copy:
        content: |
          uid = phajas
          gid = admin
          use chroot = no
          max connections = 4
          pid file = /var/run/rsyncd.pid
          log file = /var/log/rsyncd.log

          [media]
              path = /volume1/media
              comment = Media files
              read only = false
              list = yes
              uid = phajas
              gid = admin
        dest: /etc/rsyncd.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable rsync daemon in defaults
      lineinfile:
        path: /etc/default/rsync
        regexp: '^RSYNC_ENABLE='
        line: 'RSYNC_ENABLE=true'

    - name: Start rsync daemon
      systemd:
        name: rsync
        state: restarted
        enabled: yes

    - name: Wait for rsync daemon to start
      wait_for:
        port: 873
        timeout: 10

    - name: Check rsync daemon status
      command: systemctl status rsync
      register: rsync_status
      ignore_errors: yes

    - name: Display rsync status
      debug:
        msg: "{{ rsync_status.stdout_lines }}"
