---
- name: Setup Jellyfin media server
  hosts: torch
  become: false
  tasks:
    - name: Create Jellyfin service directory
      file:
        path: /home/phajas/services/jellyfin
        state: directory

    - name: Create Jellyfin config directory
      file:
        path: /home/phajas/services/jellyfin/config
        state: directory

    - name: Create Jellyfin cache directory
      file:
        path: /home/phajas/services/jellyfin/cache
        state: directory

    - name: Create Jellyfin container
      containers.podman.podman_container:
        name: jellyfin
        image: docker.io/jellyfin/jellyfin:latest
        restart_policy: always
        recreate: true
        ports:
          - "8096:8096"
        volumes:
          - /home/phajas/services/jellyfin/config:/config
          - /home/phajas/services/jellyfin/cache:/cache
          - /volume1/media:/media:ro

    - name: Display Jellyfin access info
      debug:
        msg: "Jellyfin is running at http://torch:8096"
