---
- name: Setup Navidrome music server
  hosts: torch
  become: false
  tasks:
    - name: Create Navidrome service directory
      file:
        path: /home/phajas/services/navidrome
        state: directory

    - name: Create Navidrome data directory
      file:
        path: /home/phajas/services/navidrome/data
        state: directory
        mode: '0777'

    - name: Create Navidrome container
      containers.podman.podman_container:
        name: navidrome
        image: docker.io/deluan/navidrome:latest
        recreate: true
        network: traefik
        ports:
          - "4533:4533"
        volumes:
          - /home/phajas/services/navidrome/data:/data
          - /volume1/media/music:/music:ro
        env:
          TZ: America/Denver
          ND_LOGLEVEL: info
        label:
          traefik.enable: "true"
          traefik.docker.network: "traefik"
          traefik.http.routers.navidrome.rule: "Host(`navidrome.penny.lol`)"
          traefik.http.routers.navidrome.entrypoints: "web,websecure"
          traefik.http.routers.navidrome.tls: "true"
          traefik.http.routers.navidrome.tls.certresolver: "namecheap"
          traefik.http.services.navidrome.loadbalancer.server.port: "4533"
        generate_systemd:
          path: /home/phajas/.config/systemd/user/
          restart_policy: always
          new: true

    - name: Enable Navidrome systemd service
      ansible.builtin.systemd:
        name: container-navidrome
        enabled: yes
        scope: user
        daemon_reload: yes

    - name: Display Navidrome access info
      debug:
        msg: "Navidrome is running at http://torch:4533"
