---
- name: Setup Jellyfin media server
  hosts: torch
  become: false
  tasks:
    - name: Create Jellyfin service directory
      file:
        path: /home/phajas/services/jellyfin
        state: directory

    - name: Create Jellyfin config directory
      file:
        path: /home/phajas/services/jellyfin/config
        state: directory

    - name: Create Jellyfin cache directory
      file:
        path: /home/phajas/services/jellyfin/cache
        state: directory

    - name: Create Jellyfin container
      containers.podman.podman_container:
        name: jellyfin
        image: docker.io/jellyfin/jellyfin:latest
        recreate: true
        group_add:
          - keep-groups
        ports:
          - "8096:8096"
        volumes:
          - /home/phajas/services/jellyfin/config:/config
          - /home/phajas/services/jellyfin/cache:/cache
          - /volume1/media:/media:ro
        device:
          - /dev/dri:/dev/dri
        env:
          TZ: America/Denver
          LIBVA_DRIVER_NAME: iHD
        generate_systemd:
          path: /home/phajas/.config/systemd/user/
          restart_policy: always
          new: true

    - name: Enable Jellyfin systemd service
      ansible.builtin.systemd:
        name: container-jellyfin
        enabled: yes
        scope: user
        daemon_reload: yes

    - name: Display Jellyfin access info
      debug:
        msg: "Jellyfin is running at http://torch:8096"
