---
- name: Setup torch (NAS)
  hosts: torch
  become: yes
  tasks:
    - name: Download Tailscale install script
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/tailscale-install.sh
        mode: '0755'

    - name: Run Tailscale install script
      ansible.builtin.shell:
        cmd: sh /tmp/tailscale-install.sh
        creates: /usr/bin/tailscale

    - name: Start and enable Tailscale
      ansible.builtin.systemd:
        name: tailscaled
        enabled: yes
        state: started

    - name: Connect to Tailscale network
      ansible.builtin.command:
        cmd: tailscale up
      register: tailscale_up
      changed_when: "'Success' in tailscale_up.stdout or tailscale_up.rc == 0"
      failed_when: false
