# Reference: https://github.com/i3/i3/blob/next/etc/config

on-focus-changed = ['move-mouse window-lazy-center']
automatically-unhide-macos-hidden-apps = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 194
outer.bottom = 0
outer.top = 30
outer.right = 194

[mode.main.binding]
ctrl-alt-shift-h = 'focus left'
ctrl-alt-shift-j = 'focus down'
ctrl-alt-shift-k = 'focus up'
ctrl-alt-shift-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
j = 'resize smart +50'
k = 'resize smart -50'
enter = 'mode main'
esc = 'mode main'
alt-r = 'mode main'
r = 'mode main'

# Workspace Grouping

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.reederapp.5.macOS'
run = "move-node-to-workspace 4"

[[on-window-detected]]
# Home Assistant Web App
if.app-id = 'com.apple.Safari.WebApp.BF74555B-DD53-4683-9310-2A59A39E70B2'
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id = 'com.apple.QuickTimePlayerX'
run = "move-node-to-workspace 7"

[[on-window-detected]]
if.app-id = 'com.tiddlywiki'
run = "move-node-to-workspace 10"

[[on-window-detected]]
if.app-name-regex-substring = 'mpv'
run = "layout floating"

[[on-window-detected]]
if.app-name-regex-substring = 'com.valvesoftware.steam'
run = "layout floating"
