# Generated by colors/build.py from colors/palette.toml
# Palette variant: catppuccin_latte
# Colors rely on terminal ANSI slots provided by the palette;
# keep palette.toml in sync with your terminal for best results.

from ranger.gui.colorscheme import ColorScheme
from ranger.gui.color import *

ACCENT = blue
EMPHASIS = magenta
ERROR = red
SUCCESS = green
WARNING = yellow

class Scheme(ColorScheme):
    progress_bar_color = blue

    def use(self, context):
        fg, bg, attr = default_colors
        if context.reset:
            return default_colors

        if context.in_browser:
            if context.selected:
                attr |= reverse
            if context.marked:
                attr |= bold
                fg = WARNING
            if context.bad:
                fg = ERROR
                attr |= bold
            elif context.directory:
                fg = ACCENT
            elif context.link:
                fg = cyan if not context.bad else ERROR
            elif context.fifo or context.socket:
                fg = EMPHASIS
            elif context.executable and not context.directory:
                fg = SUCCESS
                attr |= bold
            elif context.media:
                fg = EMPHASIS
            if context.inactive_pane:
                attr |= dim

        elif context.in_titlebar:
            attr |= bold
            if context.hostname:
                fg = SUCCESS if not context.bad else ERROR
            elif context.directory:
                fg = ACCENT
            elif context.tab:
                fg = cyan if context.good else ACCENT
            elif context.link:
                fg = cyan

        elif context.in_statusbar:
            if context.permissions:
                if context.good:
                    fg = SUCCESS
                elif context.bad:
                    fg = ERROR
            if context.marked:
                attr |= bold | reverse
            if context.message:
                fg = default

        if context.text:
            if context.highlight:
                attr |= reverse
            if context.bad:
                fg = ERROR

        if context.in_taskview:
            if context.title:
                attr |= bold
                fg = ACCENT
            if context.selected:
                attr |= reverse
            if context.loaded:
                fg = SUCCESS
            if context.failed:
                fg = ERROR

        return fg, bg, attr
